### PR TITLE
Implement the new zigpy radio API

### PR DESCRIPTION
**Pull request by puddly**
zigpy-zigate is the last radio library remaining.

Parent issues:

 - https://github.com/zigpy/zigpy/issues/842
 - https://github.com/zigpy/zigpy/pull/848
 - https://github.com/zigpy/zigpy-cli/pull/2

@pipiche38 I do not have a ZiGate so this code is untested beyond the unit tests. They pass with the modified version of zigpy.

### CODE REVIEW

**Comment by puddly** [comment]
Zigpy will be migrating to the simpler radio API in the very near future so it would be great if we can merge the new features in https://github.com/zigbeefordomoticz/zigpy-zigate back into zigpy/zigpy-zigate.

ZHA users will definitely benefit from broadcast support, since zigpy can't currently send a permit broadcast to all routers.

**Comment by pipiche38** [comment]
I give a try but it didn't work.

```
Feb 10 22:34:40 rasp domoticz[25092]:     self.run()
Feb 10 22:34:40 rasp domoticz[25092]:   File "/usr/lib/python3.9/threading.py", line 910, in run
Feb 10 22:34:40 rasp domoticz[25092]:     self._target(*self._args, **self._kwargs)
Feb 10 22:34:40 rasp domoticz[25092]:   File "/var/lib/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py", line 73, in zigpy_thread
Feb 10 22:34:40 rasp domoticz[25092]:     asyncio.run(
Feb 10 22:34:40 rasp domoticz[25092]:   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
Feb 10 22:34:40 rasp domoticz[25092]:     return loop.run_until_complete(main)
Feb 10 22:34:40 rasp domoticz[25092]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Feb 10 22:34:40 rasp domoticz[25092]:     return future.result()
Feb 10 22:34:40 rasp domoticz[25092]:   File "/var/lib/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py", line 91, in radio_start
Feb 10 22:34:40 rasp domoticz[25092]:     self.app = App_zigate(config)
Feb 10 22:34:40 rasp domoticz[25092]: TypeError: Can't instantiate abstract class App_zigate with abstract method shutdown
```

And that is not my part. Will see how to work on that except if you have any idea ...

**Comment by puddly** [comment]
Zigpy was updated too. You will need to install modified version of zigpy and zigpy-znp to test it:

```bash
# May need to uninstall zigpy-znp, zigpy, and zigpy-zigate first
pip install \
    git+https://github.com/puddly/zigpy.git@puddly/new-radio-settings-api \
    git+https://github.com/puddly/zigpy-znp.git@puddly/new-radio-settings-api \
    git+https://github.com/puddly/zigpy-zigate.git@puddly/new-radio-api \
```

**Comment by pipiche38** [comment]
Ok. I'll see what we can do, because it is breaking what we have done on fork() this will not be an easy step

**Comment by Hedda** [comment]
> I do not have a ZiGate so this code is untested beyond the unit tests. They pass with the modified version of zigpy.

@fairecasoimeme Do you know any ZiGate users of [Home Assistant's ZHA integration](https://www.home-assistant.io/integrations/zha) (or the Jeedom plugin) who could test this?

@zoic21 Do you know ZiGate users of [Jeedom Official Zigbee Plugin](https://github.com/zigpy/zigpy/discussions/725) who could test modified versions of zigpy and zigpy-znp?

As per https://github.com/zigpy/zigpy-zigate/issues/116 and https://github.com/zigpy/zigpy/discussions/880 there is currently no active developers or testers of https://github.com/zigpy/zigpy-zigate today.

> Zigpy was updated too. You will need to install modified version of zigpy and zigpy-znp to test it:
> 
> ```shell
> # May need to uninstall zigpy-znp, zigpy, and zigpy-zigate first
> pip install \
>     git+https://github.com/puddly/zigpy.git@puddly/new-radio-settings-api \
>     git+https://github.com/puddly/zigpy-znp.git@puddly/new-radio-settings-api \
>     git+https://github.com/puddly/zigpy-zigate.git@puddly/new-radio-api
> ```

**Comment by pipiche38** [comment]
> > I do not have a ZiGate so this code is untested beyond the unit tests. They pass with the modified version of zigpy.
> 
> @fairecasoimeme Do you know any ZiGate users of [Home Assistant's ZHA integration](https://www.home-assistant.io/integrations/zha) (or the Jeedom plugin) who could test this?
> 
> @zoic21 Do you know any ZiGate users of [Jeedom Official Zigbee Plugin](https://github.com/zigpy/zigpy/discussions/725) who could test modified versions of zigpy and zigpy-znp?
> 
> As per #116 and [zigpy/zigpy#880](https://github.com/zigpy/zigpy/discussions/880) there is currently no active developers or testers of https://github.com/zigpy/zigpy-zigate today.
> 
> > Zigpy was updated too. You will need to install modified version of zigpy and zigpy-znp to test it:
> > ```shell
> > # May need to uninstall zigpy-znp, zigpy, and zigpy-zigate first
> > pip install \
> >     git+https://github.com/puddly/zigpy.git@puddly/new-radio-settings-api \
> >     git+https://github.com/puddly/zigpy-znp.git@puddly/new-radio-settings-api \
> >     git+https://github.com/puddly/zigpy-zigate.git@puddly/new-radio-api
> > ```

What about bellows ?

**Comment by zigbeefordomoticz** [comment]
Will setting extendedPanId will also be integrated ?

As this is key got the legacy wiser devices

Envoyé de mon iPhone

**Comment by puddly** [comment]
This should in theory already be possible but I have not tested it with zigate: 

```Python
# This is already done when the network is started
await self.load_network_info()

await self.write_network_info(
    node_info=self.node_info,
    network_info=self.network_info.replace(
        extended_pan_id=zigpy.types.EUI64.convert("aa:bb:cc:dd:11:22:33:44")
    ),
)
```

It is expected to work with any radio library implementing the new API.

**Comment by pipiche38** [comment]
> It's implemented as well: [zigpy/bellows#445](https://github.com/zigpy/bellows/pull/445). See [zigpy/zigpy-cli#2](https://github.com/zigpy/zigpy-cli/pull/2) for links to PRs for all of the other radio libraries.
> 
> The only change is adding `start_network` and `disconnect`, and then moving high-level network formation code into zigpy so radios don't have to implement `form_network` directly. Everything else stays the same.
> 
> The API is provisional so if you think it needs to be changed, this would be the time to make those changes relating to network formation (or maybe adding `set_tx_power` and `set_led` as standard methods?).

So I'm afraid that I didn't understand your PR, and as your PR cannot be easily merged with our fork, I'll see how do it later when free time.

**Comment by doudz** [comment]
Many tests are failing, could you please fix your code or fix tests ?

**Comment by puddly** [comment]
This is a draft PR that makes zigpy-zigate compatible with the changes in https://github.com/zigpy/zigpy/pull/848.  All tests pass when the above branch of zigpy is installed.

**Comment by pipiche38** [comment]
Didn’t you have the possibility to keep compatibility with the old API ? This would have provided a smooth transition and especially as you change the name of the API.



Envoyé de mon iPhone

**Comment by puddly** [comment]
What's incompatible?  The only breaking change is `app.pan_id` and similar properties becoming `app.state.network_info.pan_id` and `pre_shutdown` being renamed to `shutdown`.  It's a fairly minimal change.

That being said, it's a draft PR.  If you have concrete suggestions for changes before I merge the zigpy PR, let me know.

**Comment by zigbeefordomoticz** [comment]
Basically my point is can I still use the old-fashion radio API, when you’ll release zigpy (which work with the new one )

**Comment by Hedda** [comment]
> Hi, I can test the combination of zigate usb v1 and home assistant. Installed in docker on raspi4… just need some description how to do it and how to roll back if not working well…

@Kratax FYI, a step-by-step guide is lacking but there is some indirectly related discussion about how to best test a fork in https://github.com/zigpy/zigpy-zigate/issues/104

**Comment by Hedda** [comment]
> What's incompatible? The only breaking change is `app.pan_id` and similar properties becoming `app.state.network_info.pan_id` and `pre_shutdown` being renamed to `shutdown`. It's a fairly minimal change.

I guess he means that would be nice for them if `pre_shutdown` and `NetworkInformation` will be deprecated but could still be used in parallel until they get a chance to implement the new properties? So think he is asked if could for example map `pre_shutdown` to `shutdown` and `NetworkInformation` to `NetworkInfo` so that they can use both for a while during a transition period in order to not break backwards compatibility in one single release?

I understand larger projects usually does so in order to give third-party applications using their library as dependencies a grace period. The benefit to third-party applications is that the breaking change is postponed but they still get notified that it is coming and old properties will be removed, however, the downside for upstream is that need to track deprecated changes and plan to remove them later.

**Comment by pipiche38** [comment]
What I mean is  very simple, you bring new API without breaking backward compatibility.
I just tried now, to work on the new API, nor Zigate, nor ZNP works.

So I just gave up, and will continue to use the old radio Api for now until someone is able to do the required changes on our side.

**Comment by SylvainPer** [comment]
Hello @puddly ,
I encounter some problem with the load_network_function (https://github.com/puddly/zigpy-zigate/blob/bc2e6a4ae13f572efca1714a3b355638474f6a6f/zigpy_zigate/zigbee/application.py#L62) 
Seems that zigpy calls it with some argument and it's not managed.

I try to add it but I'm stuck just after:
 File "Domoticz-Zigbee/zigpy_zigate/zigbee/application.py", line 70, in load_network_info                 
    epid, _ = zigpy.types.ExtendedPanId.deserialize(zigpy.types.uint64_t(network_state[3]).serialize())                                   
  File "Domoticz-Zigbee/zigpy/types/basic.py", line 59, in __new__                                         
    n = super().__new__(cls, *args, **kwargs)

**Comment by puddly** [comment]
You are correct, `load_network_info(self, *, load_devices=False) -> None:` is the correct signature.

@fairecasoimeme sent me a ZiGate USB (thank you!) so I will be able to fully test this PR when it arrives.

**Comment by pipiche38** [comment]
@puddly  how would you like us to do for the PR ?
We can push straight what we have done, which can be brutal, or do you want us to break it down in small PRs ?

**Comment by puddly** [comment]
@pipiche38 I'm fixing up a few problems with my changes to zigpy-zigate now that I can test it out.  We can figure out a good way to merge https://github.com/zigbeefordomoticz/zigpy-zigate/ into zigpy once I can test it out with a live ZHA network.

To make testing easier (and so I can implement `write_network_info`), do you know of a way to read/write the ZiGate PDM at runtime with normal firmware?  There is a `E_SL_MSG_LOAD_PDM_RECORD_REQUEST = 0x0201` command but it doesn't seem to be implemented in my firmware.

**Comment by pipiche38** [comment]
> @pipiche38 I'm fixing up a few problems with my changes to zigpy-zigate now that I can test it out. We can figure out a good way to merge https://github.com/zigbeefordomoticz/zigpy-zigate/ into zigpy once I can test it out with a live ZHA network.
> 
great news ... thanks for the update

> To make testing easier (and so I can implement `write_network_info`), do you know of a way to read/write the ZiGate PDM at runtime with normal firmware? There is a `E_SL_MSG_LOAD_PDM_RECORD_REQUEST = 0x0201` command but it doesn't seem to be implemented in my firmware.

I have no clue, please check with @fairecasoimeme who is the firmware provider for the ZiGate

**Comment by pipiche38** [comment]
#120

**Comment by puddly** [comment]
I'm not looking to significantly rewrite the zigpy-zigate library in this PR, only to make it compatible with the new radio API and fix whatever bugs exist that prevent a network from at least functioning.

At the moment the only task left is to write unit tests for the bellows changes and to runtime test zigpy-xbee. Once that is done and the PRs are merged, we can deal with fixing zigpy-zigate's request methods.

**Comment by pipiche38** [comment]
@puddly , I found that https://github.com/fairecasoimeme/ZiGate/blob/5a64452e3cc4f32afe217a332d0c9b1d97e17d84/ModuleRadio/Firmware/src/ZiGate/Source/ZigbeeNodeControlBridge/app_start.c#L1191 which can be interested for you as regards to a Backup/Restore solution.
If we take in consideration this procedure is used when the PDM size is changed during a firmware upgrade, we might think that can be used for Backup and then Restore.

**Comment by puddly** [comment]
@doudz Could you make a release of zigpy-zigate incorporating this PR? Or, if you're okay with it, I can make a 0.9.0 release?

I'm hoping to get the new radio library changes into HA's upcoming 2022.7.0 beta.

**Comment by doudz** [comment]
Hi!
I think you should make the release yourself, I haven't followed the latest changes ;)

**Pull request merged**
