### PR TITLE
Update URL for both travis-ci and coveralls

### PR DESCRIPTION
**Pull request by Hedda**
Update URL for both travis-ci and coveralls

### CODE REVIEW

**Comment by Adminiuga** [comment]
for some reason https://coveralls.io/repos/github/zigpy/zigpy-zigate/badge.svg?branch=master and https://coveralls.io/github/zigpy/zigpy-zigate?branch=master URLs are not working

**Comment by Hedda** [comment]
@Adminiuga do you or @doudz have to first create a zigpy/zigpy-zigate page on https://coveralls.io ?

**Comment by doudz** [comment]
Not yet, it's still doudz/zigpy-zigate

**Comment by doudz** [comment]
Done

**Pull request merged**
